// scripts/seed-data.ts
// The BLacklight slate, shared by both migration runners so they can never
// drift apart. Edit here; both scripts pick it up.

import type { Film } from '../lib/films';

/**
 * The five BLacklight titles. These don't exist in the legacy collection yet
 * (it only has Wes's directing credits through Black Heat), so they get seeded.
 */
export const BLACKLIGHT_FILMS: Film[] = [
  {
    slug: 'wildcards',
    title: 'Wildcards',
    year: '2026',
    status: 'in-theaters',
    statusLabel: 'In theaters Aug 27',
    genre: 'Courtroom thriller',
    director: 'Wes Miller',
    writer: 'Wes Miller',
    role: 'Director / Writer',
    starring: 'Leon, Elise Neal, Aries Spears, Stakiah Lynn Washington, Crew Morrow',
    producers: 'Andrew van den Houten, Wes Miller',
    company: 'blacklight',
    distributor: 'BLacklight / Dark Star Pictures',
    awards: ['Best Narrative Feature — Essence Film Festival, 2025'],
    poster: 'images/WildCards_27x40_social.jpg',
    whereToWatch: [{ platform: 'Tickets', url: 'https://wildcardslive.com' }],
    sites: ['blacklight', 'iamwesmiller'],
    order: 1,
  },
  {
    slug: 'bloody-night',
    title: 'Bloody Night',
    year: '2026',
    status: 'post',
    genre: 'Thriller',
    director: 'Wes Miller',
    role: 'Director / Writer',
    starring: 'Leon, Hannaha Hall, NLE Choppa, Jack Wright',
    company: 'blacklight',
    distributor: 'BLacklight / Dark Star Pictures',
    sites: ['blacklight', 'iamwesmiller'],
    order: 2,
  },
  {
    slug: 'mercy-mercy-me',
    title: 'Mercy Mercy Me',
    year: '2027',
    status: 'post',
    genre: 'Crime drama',
    logline: 'The prequel to Black Heat.',
    director: 'Wes Miller',
    role: 'Director / Writer',
    starring: 'Lil Mama, Jason Mitchell',
    company: 'blacklight',
    sites: ['blacklight', 'iamwesmiller'],
    order: 3,
  },
  {
    slug: 'black-heat',
    title: 'Black Heat',
    year: '2025',
    status: 'released',
    genre: 'Action',
    logline: 'After their fifteen-year-old daughter goes missing, two parents take her rescue into their own hands — a dangerous mission to infiltrate a high-level drug dealer\u2019s apartment complex.',
    director: 'Wes Miller',
    writer: 'Wes Miller',
    role: 'Director / Writer / Producer',
    starring: 'Jason Mitchell, Tabatha "DreamDoll" Robinson, NLE Choppa, Garrett Hendricks',
    producers: 'Andrew van den Houten, Wes Miller',
    company: 'blacklight',
    distributor: 'BLacklight / Dark Star Pictures',
    poster: 'images/1761880674828-optimized-BlackHeat_27x40_Main_LoRes.jpg',
    sites: ['blacklight', 'iamwesmiller'],
    order: 4,
  },
  {
    slug: 'call-her-king',
    title: 'Call Her King',
    year: '2023',
    status: 'released',
    genre: 'Action heist',
    logline: 'A federal judge fights back when her courtroom is seized.',
    director: 'Wes Miller',
    role: 'Director',
    starring: 'Naturi Naughton, Lance Gross, Jason Mitchell, Nick Turturro',
    company: 'blacklight',
    poster: 'images/1761883107227-optimized-CallHerKing_27x40_MainA_HiRes.jpg',
    whereToWatch: [{ platform: 'BET+', url: '' }],
    sites: ['blacklight', 'iamwesmiller'],
    order: 5,
  },
];
