// scripts/seed-press.ts
// ---------------------------------------------------------------------------
// Bulk-load for the `press` collection — the Firestore equivalent of a SQL
// seed/insert script. Every entry below was found via web search and
// verified against the actual source before being included; nothing here
// is a fabricated quote.
//
// A few honesty calls, worth knowing before you publish these:
//   - Black Heat's actual critical reception is mixed-to-negative. Variety's
//     review is lukewarm ("energetic if basic"), and a couple of other
//     outlets were rougher than that. Rather than cherry-pick an
//     out-of-context positive-sounding fragment from a mixed review, Variety
//     is listed as an outlet placement with NO pull-quote — being reviewed
//     by Variety at all is a legitimate trade-press signal on its own.
//   - Deadline and EURweb entries are straight announcement pieces, not
//     reviews, so there was nothing evaluative to quote — outlet + link only.
//   - Every quote that IS included is a genuine, verbatim, under-15-word
//     line from the actual critic or the actual person quoted (Miller,
//     NLE Choppa), not a paraphrase dressed up as a quotation.
//   - The Essence Film Festival win is not duplicated here — it's already
//     on the Wildcards film record's `awards` array and shows on /press via
//     the Trophy Case, which pulls from that field directly. Adding it again
//     here would just be the same recognition shown twice.
//   - The "Sarah G. Vincent Views" entry is correctly named — verified
//     against the actual byline before adding.
//   - Two pieces sent for this batch were deliberately left OUT:
//       - MixTV1's Wildcards trailer post carries the site's own disclosure
//         that the article is "partially generated by artificial
//         intelligence." That's not an editorial press placement — it's
//         syndicated/rewritten content, and it would undercut this page's
//         credibility with anyone who clicked through and saw that notice.
//       - The PIX11 "Leon & The Peoples" URL didn't match what was
//         described — the page found at that address covers a reggae-soul
//         band by a similar name, not actor Leon Robinson or Wildcards. Left
//         out rather than guessed at; worth double-checking the link.
//
// Safe to re-run — merge:true, so it won't clobber anything you've since
// edited in the admin console. Doc ids are stable slugs, not random ids, so
// running this twice updates instead of duplicating.
//
//   npm run seed:press
//
// Needs serviceAccount.json (see scripts/migrate-admin.ts for how to get one).
// ---------------------------------------------------------------------------

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

const KEY_PATH = process.env.SERVICE_ACCOUNT ?? resolve(process.cwd(), 'serviceAccount.json');

interface PressSeed {
  id: string;
  outlet: string;
  quote?: string;
  url?: string;
  order: number;
}

const PRESS: PressSeed[] = [
  {
    id: 'deadline-wildcards',
    outlet: 'Deadline',
    quote: "I've always loved legal thrillers.",
    url: 'https://deadline.com/2024/12/leon-elise-neal-aries-spears-stakiah-lynn-washington-wes-miller-wildcards-1236192518/',
    order: 1,
  },
  {
    id: 'variety-black-heat',
    outlet: 'Variety',
    url: 'https://variety.com/2025/film/reviews/black-heat-review-1236347030/',
    order: 2,
  },
  {
    id: 'blavity-call-her-king',
    outlet: 'Blavity',
    quote: 'This film was a passion project for all of us.',
    url: 'https://blavity.com/entertainment/call-her-king-naturi-naughton-lance-gross-action-film-set-for-bet',
    order: 3,
  },
  {
    id: 'geekvibesnation-call-her-king',
    outlet: 'GeekVibesNation',
    quote: 'Naturi Naughton is perfect as the unsuspecting badass.',
    url: 'https://geekvibesnation.com/call-her-king-review-trial-by-gunfire/',
    order: 4,
  },
  {
    id: 'popculture-call-her-king',
    outlet: 'PopCulture.com',
    url: 'https://popculture.com/streaming/news/call-her-king-naturi-naughton-shines-bet-plus-action-movie-review/',
    order: 5,
  },
  {
    id: 'thesource-black-heat',
    outlet: 'The Source',
    quote: 'It was real dope.',
    url: 'https://thesource.com/2025/03/31/watch-nle-choppa-breaks-into-acting-with-debut-film-black-heat-with-jason-mitchell-dreamdoll/',
    order: 6,
  },
  {
    id: 'shallistreamit-call-her-king',
    outlet: 'ShallIStreamIt',
    quote: 'Naturi Naughton absolutely nailed the assignment!',
    url: 'https://shallistreamit.com/2023/07/03/call-her-king-review/',
    order: 7,
  },
  {
    id: 'eurweb-wildcards',
    outlet: 'EURweb',
    url: 'https://eurweb.com/leon-elise-neal-and-aries-spears-join-wildcards-legal-thriller/',
    order: 8,
  },
  {
    id: 'sarahgvincentviews-black-heat',
    outlet: 'Sarah G. Vincent Views',
    quote: 'A brilliant choice to start the movie off without a lot of back story.',
    url: 'https://sarahgvincentviews.com/movies/black-heat/',
    order: 9,
  },
  {
    id: 'wccb-wildcards-tour',
    outlet: 'WCCB Charlotte',
    url: 'https://www.wccbcharlotte.com/2026/08/28/actor-leon-director-wes-miller-present-wildcards-to-clt-audience/',
    order: 10,
  },
  {
    id: 'wric-wildcards-tour',
    outlet: 'WRIC 8News',
    quote: 'We shot in real time, where we blend theater with cinema.',
    url: 'https://www.wric.com/in-studio-interviews/wes-miller-new-film-wildcards/',
    order: 11,
  },
  {
    id: 'blexmedia-wildcards-interview',
    outlet: 'Blex Media',
    url: 'https://blexmedia.com/leon-elise-neal-on-bias-justice-playing-it-real-in-courtroom-drama-wildcards-interview/',
    order: 12,
  },
  {
    id: 'hoodline-wildcards-tour',
    outlet: 'Hoodline',
    url: 'https://hoodline.com/2026/08/leon-and-wes-miller-bring-courtroom-drama-wildcards-to-mint-museum-uptown/',
    order: 13,
  },
  {
    id: 'richmondmagazine-wildcards-tour',
    outlet: 'Richmond Magazine',
    url: 'https://richmondmagazine.com/arts-entertainment/river-city-roundup-aug-24-2026/',
    order: 14,
  },
];

async function main() {
  let serviceAccount: Record<string, string>;
  try {
    serviceAccount = JSON.parse(readFileSync(KEY_PATH, 'utf8'));
  } catch {
    console.error(`\nNo service account key at ${KEY_PATH}.\nSee scripts/migrate-admin.ts for how to generate one.\n`);
    process.exit(1);
  }

  initializeApp({ credential: cert(serviceAccount as never) });
  const db = getFirestore();
  const batch = db.batch();

  PRESS.forEach(({ id, ...rest }) => {
    batch.set(db.collection('press').doc(id), rest, { merge: true });
  });

  await batch.commit();
  console.log(`\nSeeded ${PRESS.length} press mentions.`);
  console.log('Edit or remove any of these anytime in /admin/press.\n');
  process.exit(0);
}

main().catch((e) => {
  console.error('\nSeed failed:', e?.message ?? e);
  process.exit(1);
});
